### ISSUE TITLE
LITTLE_ENDIAN is commented out in some devices, not others (and causes errors while building)

### ISSUE THREAD

**Issue by barawn** [adafruit/asf4#31]
All of the samd21 files in samd21/include have a "#define LITTLE_ENDIAN 1", but some of them have it commented out (samd21e18a.h, samd21g18a.h, samr21g18a.h).

When I tried to build for a different device (a SAMD21J18A), the fact that it wasn't commented out caused build errors:

> In file included from asf4/samd21/include/sam.h:58:0,
>                  from ./mpconfigport.h:31,
>                  from ../../py/mpconfig.h:45,
>                  from ../../py/gc.h:31,
>                  from ../../py/gc.c:31:
> asf4/samd21/include/samd21j18a.h:228:0: error: "LITTLE_ENDIAN" redefined [-Werror]
>  #define LITTLE_ENDIAN          1
> 
> In file included from /usr/include/newlib/sys/types.h:67:0,
>                  from /usr/include/newlib/stdio.h:61,
>                  from ../../py/gc.c:28:
> /usr/include/newlib/machine/endian.h:17:0: note: this is the location of the previous definition
>  #define LITTLE_ENDIAN _LITTLE_ENDIAN
> 
> cc1: all warnings being treated as errors
> 

I commented it out in the samd21j18a.h file, and (after fixing separate issues in samd-peripherals) it built fine. But I'm not sure if the right solution is just commenting it out everywhere here?

**Comment by tannewt** [comment]
Commenting it out was the simplest for us and I'd be happy to merge in a PR that comments it out in more places.
