### ISSUE TITLE
libwebsockets + asf for atmel SAM4E - mbedtls issue when i try to use minimal lws client 

### ISSUE THREAD

**Issue by ghost** [adafruit/asf4#39]
Hi all.
I have just generated Atmel sam4e's libwebsockets.a from libwebsockets project.
I have arrived to test my libwebsockets.a lib. i have some issue to test it as ws-client.
You can see this link for more about adding (mbedtls to lws and add lws to asf ): https://github.com/warmcat/libwebsockets/issues/2025

I have tried to use ws-client when i compile it i got an mbedTLS error:
./lws/include/libwebsockets.h:262:29: fatal error: mbedtls/lws_config.h: No such file or directory
  262 | #define MBEDTLS_CONFIG_FILE <mbedtls/lws_config.h>

I need help to compile just a simple ws-client for atmel (sam4e), do you have an idea about the reason for this error ?

All the best

**Comment by dhalbert** [comment]
Hi, this is not a general-purpose asf4 repo; it's for use in Adafruit projects, specifically https://github.com/adafruit/circuitpython. It was constructed by using Atmel START and putting the results of a configuration in a repo.

You'll want to use a MicroChip support site like the MicroChip or Atmel forums.
