### ISSUE TITLE
ASF4 - Astart file up to date?

### ISSUE THREAD

**Issue by BrianAtDocumentedDesigns** [adafruit/asf4#40]
Hello

I don't know if this is an issue, a problem with my understanding of Atmel Start, or some other thing. 
In the Adafruit asf4 repository /SAMD51 there is an file 

    "atmel_start_config.atstart"

I assume this is the source for Atmel Start to produce the other files, however, when I go to start.atmel.com and load atmel_start_config.atstart, the resulting clock configuration is "strange" if you look at in in Atmel Start. When I subsequently export the project I get completely different files. Most of the differences are immaterial (copyright notices) but several important files (hpl_gclk.c, hpl_osc32kctrl.c, hpl_oscctrl.c, and others) seem to be somewhat different.

Many of these differences are likely Atmel bug fixes, however, it is possible that the atmel_start_config.atstart file is obsolete or perhaps Start is parsing it differently. 

I have a problem in that I hang at a hri_gclk_wait_for_sync(hw, GCLK_SYNCBUSY_SWRST); in hri_glck_d51.h and these "... wait_for_sync(" calls are no present in the Adafruit files.

I suspect my problem is that the clock configuration produced by Atmel Start is wrong. I was wondering if there was an update version of the .astart file or even this repository.

Thanks

**Comment by dhalbert** [comment]
Hi - We only used the `.atstart` files to download all the relevant header and driver files that we needed, for all the peripherals we support. We then had to fix a few bugs in ASF4, so there are multiple branches in this repo, which reflect that.

We have not tried to regenerate these files in a long time, and have not tried to keep up with ASF4 fixes. It is very painful to regenerate these files with Atmel START and then try to do a merge and figure out which changes we need.

We have found that the clock configuration GUI in Atmel START seems to be buggy, at least in the past. Reasonable clock configurations were not settable or produced errors in the GUI. We have our own code for clock configuration.

Quite frankly, we were much happier with the ASF3 approach. We only went to ASF4 to support the SAMD51, which was not supported by ASF3. If we could find an alternative that was a straightforward tar ball download, we would use that. We do pin allocation and setup at run-time, not compile-time, and the ASF4 header-file approach does not match our use case.

**Comment by BrianAtDocumentedDesigns** [comment]
Thanks for the reply. That's pretty much why I went with ASF4 as well: no support for SAMD51 in ASF3 and, as it turns out, garbage support for SAMD51 in ASF4 as (no real useable applications). Unfortunately, I absolutely hate Arduino platform and I'm doing bare metal on a Metro M4 and that is much harder than I expected thanks to Atmel/Microchip. 

I'm sure I'll figure it out eventually.

Thanks for the quick feedback

**Comment by tannewt** [comment]
@BrianAtDocumentedDesigns take a look at https://github.com/adafruit/samd-peripherals it's a very light wrapper above/around ASF4 that we use in circuitpython. It might have some pythonism leaked into it but we can refactor them out if you need it.
